# repo-a/.github/workflows/trigger-repo-b.yml
name: Trigger Repo B Workflow

on:
  push:
    branches:
      - main  # or your desired branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B via repository_dispatch
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/<your-org-or-user>/repo-b/dispatches \
            -d '{"event_type": "trigger-docker-build"}'
